name: pytest

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Run the pytest script.'
        required: false
        default: ""
  push:
    branches: [ main, staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dev tools
        env:
          MRSM_SKIP_DOCKER_EXPERIMENTAL: 1
        run: ./scripts/setup.sh
      - name: Install db drivers
        run: sudo ./scripts/drivers.sh
      - name: Image setup
        run: sudo ./scripts/docker/image_setup.sh
      - name: pytest
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: ./scripts/test.sh db
