name: pytest

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Run the pytest script.'
        required: false
        default: ""
  push:
    branches: [ main, staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dev tools
        env:
          MRSM_SKIP_DOCKER_EXPERIMENTAL: 1
        run: ./scripts/setup.sh
      - uses: actions/cache@v3
        with:
          path: /tmp/_oracle.rpm
          key: ${{ runner.os }}
      - name: Install db drivers
        run: sudo ./scripts/drivers.sh
      - name: Image setup
        run: |
          sudo MRSM_USER=meerschaum \
          MRSM_HOME=/home/meerschaum \
          MRSM_ROOT_DIR=/meerschaum \
          MRSM_WORK_DIR=/meerschaum \
          MRSM_DEP_GROUP=minimal \
          ./scripts/docker/image_setup.sh
      - name: Integration tests
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: ./scripts/test.sh db
